# This is an autogenerated file -- Do not edit
# Edit the source file in artisan/doc/help_dialogs/Input_files
# then execute artisan/doc/help_dialogs/Script/xlsx_to_artisan_help.py
import prettytable
import re
from PyQt6.QtWidgets import QApplication

def content() -> str:
    strlist = []
    helpstr = ''  # noqa: F841 #@UnusedVariable # pylint: disable=unused-variable
    newline = '\n'  # noqa: F841 #@UnusedVariable  # pylint: disable=unused-variable
    strlist.append('<head><style> td, th {border: 1px solid #ddd;  padding: 6px;} th {padding-top: 6px;padding-bottom: 6px;text-align: left;background-color: #0C6AA6; color: white;} </style></head> <body>')
    strlist.append('<b>')
    strlist.append(QApplication.translate('HelpDlg','PORTS CONFIGURATION'))
    strlist.append('</b>')
    tbl_MQTT = prettytable.PrettyTable()
    tbl_MQTT.field_names = [QApplication.translate('HelpDlg','MQTT SETTINGS')]
    tbl_MQTT.add_row([QApplication.translate('HelpDlg','The MQTT communication is respecting the broker&#39;s host IP and port for communication over TCP or WebSockets using the MQTT protocol v3.1, v3.1.1, or v5. Encryption can be enabled by ticking the TLS option. Connect timeout and keepalive periods can be configured in seconds, and access credentials can be set.')])
    tbl_MQTT.add_row([QApplication.translate('HelpDlg','Artisan establishes a connection with the broker and subscribes to the specified topics if the ON button is pressed. Each input extracts its data from the payloads received for the main topic or, if provided, the input-specific topics. For each input, a JMESPath (jmespath.org) expression is used to determine how to extract the data for that input is extracted from the received payload.')])
    tbl_MQTT.add_row([QApplication.translate('HelpDlg','For example, for the payload {"foo": {"bar": [1, 2]}}, the JMESPath expression foo.bar[0] will result in the value 1.')])
    tbl_MQTT.add_row([QApplication.translate('HelpDlg','If mode is set to C or F, readings are automatically converted to the temperature unit set for display.')])
    strlist.append(tbl_MQTT.get_html_string(attributes={'width':'100%','border':'1','padding':'1','border-collapse':'collapse'}))
    strlist.append('</body>')
    helpstr = ''.join(strlist)
    return re.sub(r'&amp;', r'&',helpstr)
