.TH Artisan 1 "May  30, 2013" "Artisan"
.SH NAME
Artisan \- Visual Scope for Coffee Roasters
.SH SYNOPSIS
.B artisan
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B artisan
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, it has documentation in the GNU Info format; see below.
.PP
\artisan\fP helps coffee roasters record, analyze, and control
 roast profiles. With the help of a thermocouple data logger, or a
 proportional–integral–derivative controller (PID controller), this software
 offers roasting metrics to help make decisions that influence the final coffee
 flavor.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
Currently there are no options supported.
For a complete description, see the Info files.
.SH AUTHOR
This manual page was written by Marko Luther <marko.luther@gmx.net>,
for the Debian GNU/Linux system (but may be used by others).