#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# countries.py
#
# Copyright (c) 2018, Paul Holleis, Marko Luther
# All rights reserved.
# 
# 
# ABOUT
# This module connects to the artisan.plus inventory management service

# LICENSE
# This program or module is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 2 of the License, or
# version 3 of the License, or (at your option) any later versison. It is
# provided for educational purposes and is distributed in the hope that
# it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
# the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from PyQt5.QtWidgets import QApplication

QApplication.translate("Countries","Afghanistan", None)
QApplication.translate("Countries","Aland Islands", None)
QApplication.translate("Countries","Albania", None)
QApplication.translate("Countries","Algeria", None)
QApplication.translate("Countries","American Samoa", None)
QApplication.translate("Countries","Andorra", None)
QApplication.translate("Countries","Angola", None)
QApplication.translate("Countries","Anguilla", None)
QApplication.translate("Countries","ANI", None) # Andaman and Nicobar Islands
QApplication.translate("Countries","Antarctica", None)
QApplication.translate("Countries","Antigua and Barbuda", None)
QApplication.translate("Countries","Argentina", None)
QApplication.translate("Countries","Armenia", None)
QApplication.translate("Countries","Aruba", None)
QApplication.translate("Countries","Australia", None)
QApplication.translate("Countries","Austria", None)
QApplication.translate("Countries","Azerbaijan", None)
QApplication.translate("Countries","Bahamas", None)
QApplication.translate("Countries","Bahrain", None)
QApplication.translate("Countries","Bali", None)
QApplication.translate("Countries","Bangladesh", None)
QApplication.translate("Countries","Barbados", None)
QApplication.translate("Countries","Belarus", None)
QApplication.translate("Countries","Belgium", None)
QApplication.translate("Countries","Belize", None)
QApplication.translate("Countries","Benin", None)
QApplication.translate("Countries","Bermuda", None)
QApplication.translate("Countries","Bhutan", None)
QApplication.translate("Countries","Bolivia", None)
QApplication.translate("Countries","Bonaire, Sint Eustatius and Saba", None)
QApplication.translate("Countries","Borneo", None)
QApplication.translate("Countries","Bosnia and Herzegovina", None)
QApplication.translate("Countries","Botswana", None)
QApplication.translate("Countries","Bouvet Island", None)
QApplication.translate("Countries","Brazil", None)
QApplication.translate("Countries","British Indian Ocean Territory", None)
QApplication.translate("Countries","Brunei Darussalam", None)
QApplication.translate("Countries","Bulgaria", None)
QApplication.translate("Countries","Burkina Faso", None)
QApplication.translate("Countries","Burundi", None)
QApplication.translate("Countries","Cape Verde", None)
QApplication.translate("Countries","Cambodia", None)
QApplication.translate("Countries","Cameroon", None)
QApplication.translate("Countries","Canada", None)
QApplication.translate("Countries","Canary Islands", None)
QApplication.translate("Countries","Cayman Islands", None)
QApplication.translate("Countries","Central African Republic", None)
QApplication.translate("Countries","Chad", None)
QApplication.translate("Countries","Chile", None)
QApplication.translate("Countries","China", None)
QApplication.translate("Countries","Christmas Island", None)
QApplication.translate("Countries","Cocos (Keeling) Islands", None)
QApplication.translate("Countries","Colombia", None)
QApplication.translate("Countries","Comoros", None)
QApplication.translate("Countries","Congo, DR", None)
QApplication.translate("Countries","Congo, Republic", None)
QApplication.translate("Countries","Cook Islands", None)
QApplication.translate("Countries","Costa Rica", None)
QApplication.translate("Countries","Croatia", None)
QApplication.translate("Countries","Cuba", None)
QApplication.translate("Countries","Cyprus", None)
QApplication.translate("Countries","Czechia", None)
QApplication.translate("Countries","Denmark", None)
QApplication.translate("Countries","Djibouti", None)
QApplication.translate("Countries","Dominica", None)
QApplication.translate("Countries","Dominican Republic", None)
QApplication.translate("Countries","Ecuador", None)
QApplication.translate("Countries","Egypt", None)
QApplication.translate("Countries","El Salvador", None)
QApplication.translate("Countries","Equatorial Guinea", None)
QApplication.translate("Countries","Eritrea", None)
QApplication.translate("Countries","Estonia", None)
QApplication.translate("Countries","Eswatini", None)
QApplication.translate("Countries","Ethiopia", None)
QApplication.translate("Countries","Falkland Islands [Malvinas]", None)
QApplication.translate("Countries","Faroe Islands", None)
QApplication.translate("Countries","Fiji", None)
QApplication.translate("Countries","Flores", None)
QApplication.translate("Countries","Finland", None)
QApplication.translate("Countries","France", None)
QApplication.translate("Countries","French Guiana", None)
QApplication.translate("Countries","French Polynesia", None)
QApplication.translate("Countries","French Southern Territories", None)
QApplication.translate("Countries","Gabon", None)
QApplication.translate("Countries","Gambia", None)
QApplication.translate("Countries","Georgia", None)
QApplication.translate("Countries","Germany", None)
QApplication.translate("Countries","Ghana", None)
QApplication.translate("Countries","Gibraltar", None)
QApplication.translate("Countries","Greece", None)
QApplication.translate("Countries","Greenland", None)
QApplication.translate("Countries","Grenada", None)
QApplication.translate("Countries","Guadeloupe", None)
QApplication.translate("Countries","Guam", None)
QApplication.translate("Countries","Guatemala", None)
QApplication.translate("Countries","Guernsey", None)
QApplication.translate("Countries","Guinea", None)
QApplication.translate("Countries","Guinea-Bissau", None)
QApplication.translate("Countries","Guyana", None)
QApplication.translate("Countries","Haiti", None)
QApplication.translate("Countries","Hawaii", None)
QApplication.translate("Countries","Heard Island and McDonald Islands", None)
QApplication.translate("Countries","Honduras", None)
QApplication.translate("Countries","Hong Kong", None)
QApplication.translate("Countries","Hungary", None)
QApplication.translate("Countries","Iceland", None)
QApplication.translate("Countries","India", None)
QApplication.translate("Countries","Indonesia", None)
QApplication.translate("Countries","Iran", None)
QApplication.translate("Countries","Iraq", None)
QApplication.translate("Countries","Ireland", None)
QApplication.translate("Countries","Isle of Man", None)
QApplication.translate("Countries","Israel", None)
QApplication.translate("Countries","Italy", None)
QApplication.translate("Countries","Ivory Coast", None)
QApplication.translate("Countries","Jamaica", None)
QApplication.translate("Countries","Japan", None)
QApplication.translate("Countries","Java", None)
QApplication.translate("Countries","Jersey", None)
QApplication.translate("Countries","Jordan", None)
QApplication.translate("Countries","Kazakhstan", None)
QApplication.translate("Countries","Kenya", None)
QApplication.translate("Countries","Kiribati", None)
QApplication.translate("Countries","North Korea", None)
QApplication.translate("Countries","South Korea", None)
QApplication.translate("Countries","Kuwait", None)
QApplication.translate("Countries","Kyrgyzstan", None)
QApplication.translate("Countries","Laos", None)
QApplication.translate("Countries","Latvia", None)
QApplication.translate("Countries","Lebanon", None)
QApplication.translate("Countries","Lesotho", None)
QApplication.translate("Countries","Liberia", None)
QApplication.translate("Countries","Libya", None)
QApplication.translate("Countries","Liechtenstein", None)
QApplication.translate("Countries","Lithuania", None)
QApplication.translate("Countries","Luxembourg", None)
QApplication.translate("Countries","Macao", None)
QApplication.translate("Countries","Macedonia, the former Yugoslav Republic of", None)
QApplication.translate("Countries","Madagascar", None)
QApplication.translate("Countries","Malawi", None)
QApplication.translate("Countries","Malaysia", None)
QApplication.translate("Countries","Maldives", None)
QApplication.translate("Countries","Mali", None)
QApplication.translate("Countries","Malta", None)
QApplication.translate("Countries","Marshall Islands", None)
QApplication.translate("Countries","Martinique", None)
QApplication.translate("Countries","Mauritania", None)
QApplication.translate("Countries","Mauritius", None)
QApplication.translate("Countries","Mayotte", None)
QApplication.translate("Countries","Mexico", None)
QApplication.translate("Countries","Micronesia", None)
QApplication.translate("Countries","Micronesia, Federated States of", None)
QApplication.translate("Countries","Moldova", None)
QApplication.translate("Countries","Moldova, the Republic of", None)
QApplication.translate("Countries","Monaco", None)
QApplication.translate("Countries","Mongolia", None)
QApplication.translate("Countries","Montenegro", None)
QApplication.translate("Countries","Montserrat", None)
QApplication.translate("Countries","North Macedonia", None)
QApplication.translate("Countries","Morocco", None)
QApplication.translate("Countries","Mozambique", None)
QApplication.translate("Countries","Myanmar", None)
QApplication.translate("Countries","Namibia", None)
QApplication.translate("Countries","Nauru", None)
QApplication.translate("Countries","Nepal", None)
QApplication.translate("Countries","Netherlands", None)
QApplication.translate("Countries","New Caledonia", None)
QApplication.translate("Countries","New Zealand", None)
QApplication.translate("Countries","Nicaragua", None)
QApplication.translate("Countries","Niger", None)
QApplication.translate("Countries","Nigeria", None)
QApplication.translate("Countries","Niue", None)
QApplication.translate("Countries","Norfolk Island", None)
QApplication.translate("Countries","Northern Mariana Islands", None)
QApplication.translate("Countries","Norway", None)
QApplication.translate("Countries","Oman", None)
QApplication.translate("Countries","Pakistan", None)
QApplication.translate("Countries","Palau", None)
QApplication.translate("Countries","Palestine", None)
QApplication.translate("Countries","Palestine, State of", None)
QApplication.translate("Countries","Panama", None)
QApplication.translate("Countries","Papua", None)
QApplication.translate("Countries","PNG", None)
QApplication.translate("Countries","Paraguay", None)
QApplication.translate("Countries","Peru", None)
QApplication.translate("Countries","Philippines", None)
QApplication.translate("Countries","Pitcairn", None)
QApplication.translate("Countries","Poland", None)
QApplication.translate("Countries","Portugal", None)
QApplication.translate("Countries","Puerto Rico", None)
QApplication.translate("Countries","Qatar", None)
QApplication.translate("Countries","Romania", None)
QApplication.translate("Countries","Russian Federation", None)
QApplication.translate("Countries","Rwanda", None)
QApplication.translate("Countries","St. Helena", None)
QApplication.translate("Countries","Saint Kitts and Nevis", None)
QApplication.translate("Countries","St. Lucia", None)
QApplication.translate("Countries","Saint Lucia", None)
QApplication.translate("Countries","Saint Martin (French part)", None)
QApplication.translate("Countries","Saint Pierre and Miquelon", None)
QApplication.translate("Countries","St. Vincent", None)
QApplication.translate("Countries","Samoa", None)
QApplication.translate("Countries","San Marino", None)
QApplication.translate("Countries","Saudi Arabia", None)
QApplication.translate("Countries","Senegal", None)
QApplication.translate("Countries","Serbia", None)
QApplication.translate("Countries","Seychelles", None)
QApplication.translate("Countries","Sierra Leone", None)
QApplication.translate("Countries","Singapore", None)
QApplication.translate("Countries","Sint Maarten (Dutch part)", None)
QApplication.translate("Countries","Slovakia", None)
QApplication.translate("Countries","Slovenia", None)
QApplication.translate("Countries","Solomon Islands", None)
QApplication.translate("Countries","Somalia", None)
QApplication.translate("Countries","South Africa", None)
QApplication.translate("Countries","South Georgia and the South Sandwich Islands", None)
QApplication.translate("Countries","South Sudan", None)
QApplication.translate("Countries","Spain", None)
QApplication.translate("Countries","Sri Lanka", None)
QApplication.translate("Countries","Sudan", None)
QApplication.translate("Countries","Sulawesi", None)
QApplication.translate("Countries","Sumatra", None)
QApplication.translate("Countries","Sumbawa", None)
QApplication.translate("Countries","Suriname", None)
QApplication.translate("Countries","Svalbard and Jan Mayen", None)
QApplication.translate("Countries","Sweden", None)
QApplication.translate("Countries","Switzerland", None)
QApplication.translate("Countries","Syrian Arab Republic", None)
QApplication.translate("Countries","Taiwan", None)
QApplication.translate("Countries","Taiwan (Province of China)", None)
QApplication.translate("Countries","Tajikistan", None)
QApplication.translate("Countries","Tanzania", None)
QApplication.translate("Countries","Thailand", None)
QApplication.translate("Countries","Timor, East", None)
QApplication.translate("Countries","Togo", None)
QApplication.translate("Countries","Tokelau", None)
QApplication.translate("Countries","Tonga", None)
QApplication.translate("Countries","Trinidad and Tobago", None)
QApplication.translate("Countries","Trinidad & Tobago", None)
QApplication.translate("Countries","Tunisia", None)
QApplication.translate("Countries","Turkey", None)
QApplication.translate("Countries","Turkmenistan", None)
QApplication.translate("Countries","Turks and Caicos Islands", None)
QApplication.translate("Countries","Tuvalu", None)
QApplication.translate("Countries","Uganda", None)
QApplication.translate("Countries","Ukraine", None)
QApplication.translate("Countries","United Arab Emirates", None)
QApplication.translate("Countries","UK", None)
QApplication.translate("Countries","United Kingdom of Great Britain and Northern Ireland", None)
QApplication.translate("Countries","United States Minor Outlying Islands", None)
QApplication.translate("Countries","USA", None)
QApplication.translate("Countries","United States of America", None)
QApplication.translate("Countries","Uruguay", None)
QApplication.translate("Countries","Uzbekistan", None)
QApplication.translate("Countries","Vanuatu", None)
QApplication.translate("Countries","Venezuela", None)
QApplication.translate("Countries","Vietnam", None)
QApplication.translate("Countries","Virgin Islands (British)", None)
QApplication.translate("Countries","Virgin Islands (U.S.)", None)
QApplication.translate("Countries","Wallis and Futuna", None)
QApplication.translate("Countries","Western Sahara", None)
QApplication.translate("Countries","Yemen", None)
QApplication.translate("Countries","Zambia", None)
QApplication.translate("Countries","Zimbabwe", None)

# those lead to issues in the translation system due to the accent characters and are thus left out from translations for now
# (issue occurs on second run of pylupdate5 on macOS which encodes accent characters in source tags)
#QApplication.translate("Countries","Curaçao", None)
#QApplication.translate("Countries","Galápagos", None)
#QApplication.translate("Countries","Saint Barthélemy", None)
#QApplication.translate("Countries","Réunion", None)
#QApplication.translate("Countries","São Tomé", None)
