// ABOUT
// Artisan profile payload
//
// LICENSE
// This program or module is free software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation, either version 2 of the License, or
// version 3 of the License, or (at your option) any later version. It is
// provided for educational purposes and is distributed in the hope that
// it will be useful, but WITHOUT ANY WARRANTY; without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
// the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// MAINTAINER
// Marko Luther, 2026

edition = "2024";

package artisan.roast.v1;

import "google/protobuf/timestamp.proto";


message Roast {

  // NOTES
  //
  // The value -1 is used as a null value to indicate a missing
  // value in sequences of readings, such as bt_readings, et_readings,
  // bt_ror_readings, and et_ror_readings.
  //
  // INVARIANTS
  //
  // - all indices of the given milestones are valid
  //   for idx in milestones.*_idx: 0 <= idx < len(times)
  // - all annotations are well defined and valid
  //   len(annotations.time_indices) == len(annotations.tags) and
  //   for idx in annotations.time_indices: 0 <= idx < len(times)
  // - all events are well defined and valid
  //   for events in {events1, events2, events3, events4}:
  //     len(events.time_indices) == len(events.values) and
  //     for idx in events.time_indices: 0 <= idx <= len(times)
  // - all readings are valid
  //   for readings in {
  //          bt_readings, et_readings,
  //          bt_ror_readings, et_ror_readings}:
  //      len(readings) == len(time)
  //   for curve in additional_curves:
  //      len(curve.times) == len(annotationscurve.values)
  // - if milestones.charge_idx is given:
  //      times[milestones.charge_idx] = 0
  //   elif len(times)>0:
  //      times[0] = 0

  message Milestones {
    int32 charge_idx = 1;
    int32 dry_end_idx = 2;
    int32 first_crack_start_idx = 3;
    int32 first_crack_end_idx = 4;
    int32 second_crack_start_idx = 5;
    int32 second_crack_end_idx = 6;
    int32 drop_idx = 7;
  }

  message Annotations {
    repeated int32 time_indices = 1;
    repeated string tags = 2;
  }

  message Events {
    string name = 1;
    string unit = 2;
    repeated int32 time_indices = 3;
    repeated float values = 4;
  }

  // the value -1 is used as null value to indicate a missing reading in values
  message Signal {
    string name = 1;
    repeated float times = 2;
    repeated float values = 3;
  }

  string org_id = 1;           // id of organization
  string machine_id = 2;       // id of machine
  string roast_id = 3;         // roast UUID
  google.protobuf.Timestamp start = 4;
  google.protobuf.Timestamp end = 5;
  repeated float times = 6;    // [s] relative to CHARGE
  Milestones milestones = 7;   // main roasting events like CHARGE, FCs, ...
  Annotations annotations = 8; // manual placed annotations
  repeated Events events = 9;  // spares events of various types like power level
  repeated float bt_readings = 10;  // [Celsius] bean temperatures
  repeated float et_readings = 11;  // [Celsius] environmental temperatures
  repeated float bt_ror_readings = 12; // [Celsius/min] BT RoR
  repeated float et_ror_readings = 13; // [Celsius/min] ET RoR
  repeated Signal additional_curves = 14;  // additional curves
}
