# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/artisan/v1/artisan_roast.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/artisan/v1/artisan_roast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$proto/artisan/v1/artisan_roast.proto\x12\x10\x61rtisan.roast.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x06\n\x05Roast\x12\x0e\n\x06org_id\x18\x01 \x01(\t\x12\x12\n\nmachine_id\x18\x02 \x01(\t\x12\x10\n\x08roast_id\x18\x03 \x01(\t\x12)\n\x05start\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05times\x18\x06 \x03(\x11\x12\x36\n\nmilestones\x18\x07 \x01(\x0b\x32\".artisan.roast.v1.Roast.Milestones\x12\x38\n\x0b\x61nnotations\x18\x08 \x01(\x0b\x32#.artisan.roast.v1.Roast.Annotations\x12.\n\x06\x65vents\x18\t \x03(\x0b\x32\x1e.artisan.roast.v1.Roast.Events\x12\x11\n\tbt_values\x18\n \x03(\x11\x12\x11\n\tet_values\x18\x0b \x03(\x11\x12\x15\n\rbt_ror_values\x18\x0c \x03(\x11\x12\x15\n\ret_ror_values\x18\r \x03(\x11\x12\x38\n\x11\x61\x64\x64itional_curves\x18\x0e \x03(\x0b\x32\x1d.artisan.roast.v1.Roast.Curve\x12\x0e\n\x06\x66\x61\x63tor\x18\x0f \x01(\r\x1a\xc1\x01\n\nMilestones\x12\x12\n\ncharge_idx\x18\x01 \x01(\r\x12\x13\n\x0b\x64ry_end_idx\x18\x02 \x01(\r\x12\x1d\n\x15\x66irst_crack_start_idx\x18\x03 \x01(\r\x12\x1b\n\x13\x66irst_crack_end_idx\x18\x04 \x01(\r\x12\x1e\n\x16second_crack_start_idx\x18\x05 \x01(\r\x12\x1c\n\x14second_crack_end_idx\x18\x06 \x01(\r\x12\x10\n\x08\x64rop_idx\x18\x07 \x01(\r\x1a\x31\n\x0b\x41nnotations\x12\x14\n\x0ctime_indices\x18\x01 \x03(\r\x12\x0c\n\x04tags\x18\x02 \x03(\t\x1aJ\n\x06\x45vents\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x14\n\x0ctime_indices\x18\x03 \x03(\r\x12\x0e\n\x06values\x18\x04 \x03(\r\x1a;\n\x05\x43urve\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x11\x12\x14\n\x0ctemperatures\x18\x03 \x01(\x08\x62\x08\x65\x64itionsp\xe9\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.artisan.v1.artisan_roast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROAST']._serialized_start=92
  _globals['_ROAST']._serialized_end=956
  _globals['_ROAST_MILESTONES']._serialized_start=575
  _globals['_ROAST_MILESTONES']._serialized_end=768
  _globals['_ROAST_ANNOTATIONS']._serialized_start=770
  _globals['_ROAST_ANNOTATIONS']._serialized_end=819
  _globals['_ROAST_EVENTS']._serialized_start=821
  _globals['_ROAST_EVENTS']._serialized_end=895
  _globals['_ROAST_CURVE']._serialized_start=897
  _globals['_ROAST_CURVE']._serialized_end=956
# @@protoc_insertion_point(module_scope)
