#!/bin/bash
#
# postinst-artisan
#
# postinst for installing Artisan
#
# Author: Marko Luther

set -e

set_mime()
{
   xdg-mime install /usr/share/artisan/artisan-alog.xml
   xdg-icon-resource install --context mimetypes --size 16 /usr/share/artisan/icons/artisanProfile16.png application-x-artisan-alog
   xdg-icon-resource install --context mimetypes --size 32 /usr/share/artisan/icons/artisanProfile32.png application-x-artisan-alog
   xdg-icon-resource install --context mimetypes --size 64 /usr/share/artisan/icons/artisanProfile64.png application-x-artisan-alog
   xdg-icon-resource install --context mimetypes --size 128 /usr/share/artisan/icons/artisanProfile128.png application-x-artisan-alog
   xdg-icon-resource install --context mimetypes --size 256 /usr/share/artisan/icons/artisanProfile256.png application-x-artisan-alog
   xdg-mime install /usr/share/artisan/artisan-alrm.xml
   xdg-icon-resource install --context mimetypes --size 16 /usr/share/artisan/icons/artisanAlarms16.png application-x-artisan-alrm
   xdg-icon-resource install --context mimetypes --size 32 /usr/share/artisan/icons/artisanAlarms32.png application-x-artisan-alrm
   xdg-icon-resource install --context mimetypes --size 64 /usr/share/artisan/icons/artisanAlarms64.png application-x-artisan-alrm
   xdg-icon-resource install --context mimetypes --size 128 /usr/share/artisan/icons/artisanAlarms128.png application-x-artisan-alrm
   xdg-icon-resource install --context mimetypes --size 256 /usr/share/artisan/icons/artisanAlarms256.png application-x-artisan-alrm
   xdg-mime install /usr/share/artisan/artisan-apal.xml
   xdg-icon-resource install --context mimetypes --size 16 /usr/share/artisan/icons/artisanPalettes16.png application-x-artisan-apal
   xdg-icon-resource install --context mimetypes --size 32 /usr/share/artisan/icons/artisanPalettes32.png application-x-artisan-apal
   xdg-icon-resource install --context mimetypes --size 64 /usr/share/artisan/icons/artisanPalettes64.png application-x-artisan-apal
   xdg-icon-resource install --context mimetypes --size 128 /usr/share/artisan/icons/artisanPalettes128.png application-x-artisan-apal
   xdg-icon-resource install --context mimetypes --size 256 /usr/share/artisan/icons/artisanPalettes256.png application-x-artisan-apal
   xdg-mime install /usr/share/artisan/artisan-aset.xml
   xdg-icon-resource install --context mimetypes --size 16 /usr/share/artisan/icons/artisanSettings16.png application-x-artisan-aset
   xdg-icon-resource install --context mimetypes --size 32 /usr/share/artisan/icons/artisanSettings32.png application-x-artisan-aset
   xdg-icon-resource install --context mimetypes --size 64 /usr/share/artisan/icons/artisanSettings64.png application-x-artisan-aset
   xdg-icon-resource install --context mimetypes --size 128 /usr/share/artisan/icons/artisanSettings128.png application-x-artisan-aset
   xdg-icon-resource install --context mimetypes --size 256 /usr/share/artisan/icons/artisanSettings256.png application-x-artisan-aset
   xdg-mime install /usr/share/artisan/artisan-athm.xml
   xdg-icon-resource install --context mimetypes --size 16 /usr/share/artisan/icons/artisanTheme16.png application-x-artisan-athm
   xdg-icon-resource install --context mimetypes --size 32 /usr/share/artisan/icons/artisanTheme32.png application-x-artisan-athm
   xdg-icon-resource install --context mimetypes --size 64 /usr/share/artisan/icons/artisanTheme64.png application-x-artisan-athm
   xdg-icon-resource install --context mimetypes --size 128 /usr/share/artisan/icons/artisanTheme128.png application-x-artisan-athm
   xdg-icon-resource install --context mimetypes --size 256 /usr/share/artisan/icons/artisanTheme256.png application-x-artisan-athm
   xdg-mime install /usr/share/artisan/artisan-wg.xml
   xdg-icon-resource install --context mimetypes --size 16 /usr/share/artisan/icons/artisanWheel16.png application-x-artisan-wg
   xdg-icon-resource install --context mimetypes --size 32 /usr/share/artisan/icons/artisanWheel32.png application-x-artisan-wg
   xdg-icon-resource install --context mimetypes --size 64 /usr/share/artisan/icons/artisanWheel64.png application-x-artisan-wg
   xdg-icon-resource install --context mimetypes --size 128 /usr/share/artisan/icons/artisanWheel128.png application-x-artisan-wg
   xdg-icon-resource install --context mimetypes --size 256 /usr/share/artisan/icons/artisanWheel256.png application-x-artisan-wg
   return 0
}

case "$1" in
   configure)
   if dpkg-query -W xdg-utils | awk '{print $2}' 2>&1 >/dev/null; then
       set_mime;
   fi
   if dpkg-query -W udev | awk '{print $2}' 2>&1 >/dev/null; then
      udevadm control -R
   fi
   ;;

   1)
   if rpm -q xdg-utils 2>&1 >/dev/null; then
       set_mime;
   fi
   if rpm -q udev 2>&1 >/dev/null; then
      udevadm control -R
   fi
   ;;

   *)

   ;;
esac

exit 0
