
import prettytable
import re
from PyQt5.QtWidgets import QApplication
def u(x):
    return str(x)
if True:  #here just to achieve the indent
    if True:
# ----- Cut below ---------------------------------------------

        # autogenerated help pasted below

        newline = "\n"  #@UnusedVariable
        helpstr = ""
        helpstr += "<head><style>"
        helpstr += "td, th {border: 1px solid #ddd;  padding: 6px;}"
        helpstr += "th {padding-top: 6px;padding-bottom: 6px;text-align: left;background-color: #0C6AA6; color: white;}"
        helpstr += "</style></head>"
        helpstr += "<body>"
        helpstr += "<b>" + u(QApplication.translate('HelpDlg','EVENT CUSTOM BUTTONS',None)) + "</b>"
        tbl_Buttons = prettytable.PrettyTable()
        tbl_Buttons.field_names = [u(QApplication.translate('HelpDlg','COL1',None)),u(QApplication.translate('HelpDlg','COL2',None))]
        tbl_Buttons.add_row([u(QApplication.translate('HelpDlg','Button Label',None)),u(QApplication.translate('HelpDlg','Enter \\n to create labels with multiple lines. \\t is substituted by the event type.',None))])
        tbl_Buttons.add_row([u(QApplication.translate('HelpDlg','Event Description',None)),u(QApplication.translate('HelpDlg','Description of the Event to be recorded.< br>Event type Type of event to be recorded.',None))])
        tbl_Buttons.add_row([u(QApplication.translate('HelpDlg','Event Value',None)),u(QApplication.translate('HelpDlg','Value of event (1-100) to be recorded',None))])
        tbl_Buttons.add_row([u(QApplication.translate('HelpDlg','Action',None)),u(QApplication.translate('HelpDlg','Perform an action at the time of the event',None))])
        tbl_Buttons.add_row([u(QApplication.translate('HelpDlg','Documentation',None)),u(QApplication.translate('HelpDlg','depends on the action type ("{}" is replaced by the event value)',None))])
        tbl_Buttons.add_row([u(QApplication.translate('HelpDlg','Button Visibility',None)),u(QApplication.translate('HelpDlg','Hides/shows individual button',None))])
        helpstr += tbl_Buttons.get_html_string(attributes={"width":"100%","border":"1","padding":"1","border-collapse":"collapse"})
        helpstr += "<br/><br/><b>" + u(QApplication.translate('HelpDlg','COMMANDS',None)) + "</b>"
        tbl_Commands = prettytable.PrettyTable()
        tbl_Commands.field_names = [u(QApplication.translate('HelpDlg','Command Type',None)),u(QApplication.translate('HelpDlg','Command',None))]
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','Serial',None)),u(QApplication.translate('HelpDlg','ASCII serial command or binary a2b_uu(serial command)',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','Call Program',None)),u(QApplication.translate('HelpDlg','A program/script path (absolute or relative)',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','Multiple Event',None)),u(QApplication.translate('HelpDlg','Adds events of other button numbers separated by a comma: 1,2,..',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','Modbus',None)),u(QApplication.translate('HelpDlg','write([slaveId,register,value],..,[slaveId,register,value]) \nwrite register: MODBUS function 6 (int) or function 16 (float)',None))])
        tbl_Commands.add_row(['&#160;',u(QApplication.translate('HelpDlg','wcoil(slaveId,register,<bool>) \nwrite coil: MODBUS function 5',None))])
        tbl_Commands.add_row(['&#160;',u(QApplication.translate('HelpDlg','wcoils(slaveId,register,[<bool>,..,<bool>]) \nwrite coils: MODBUS function 15',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg',' ',None)),u(QApplication.translate('HelpDlg','mwrite(slaveId,register,andMask,orMask) \nmask write register: MODBUS function 22',None))])
        tbl_Commands.add_row(['&#160;',u(QApplication.translate('HelpDlg','writem(slaveId,register,value) or writem(slaveId,register,[<int>,..,<int>]) \nwrite registers: MODBUS function 16',None))])
        tbl_Commands.add_row(['&#160;',u(QApplication.translate('HelpDlg','writeWord(slaveId,register,value) \nwrite 32bit float to two 16bit int registers: MODBUS function 16',None))])
        tbl_Commands.add_row(['&#160;',u(QApplication.translate('HelpDlg','writes values to the registers in slaves specified by the given id',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','S7',None)),u(QApplication.translate('HelpDlg','getDBint(<dbnumber>,<start>) \nread int from S7 DB',None))])
        tbl_Commands.add_row(['&#160;',u(QApplication.translate('HelpDlg','getDBfloat(<dbnumber>,<start>) \nread fl oat from S7 DB',None))])
        tbl_Commands.add_row(['&#160;',u(QApplication.translate('HelpDlg','setDBint(<dbnumber>,<start>,<value>) \nwrite int to S7 DB',None))])
        tbl_Commands.add_row(['&#160;',u(QApplication.translate('HelpDlg','setDBfloat(<dbnumber>,<start>,<value>) \nwrite float to S7 DB',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','DTA',None)),u(QApplication.translate('HelpDlg','Insert Data address : value, ex. 4701:1000 and sv is 100. \nAlways multiply with 10 if value Unit: 0.1 / ex. 4719:0 stops heating',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','IO',None)),u(QApplication.translate('HelpDlg','set(n,0 ), set(n,1), toggle(n), pulse(n,t) to set Phidget IO digital output n',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','PWM',None)),u(QApplication.translate('HelpDlg',' out(n,v), toggle(n), pulse(n,t) set digital output channel n to PWM value v (0-100) on a Phidget OUT1100 \nouthub(n,v), togglehub(n), pulsehub(n,t) on a Phidget HUB',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','VOUT',None)),u(QApplication.translate('HelpDlg','out(n,v) set analog output channel n to output voltage value v in V (eg. 5.5 for 5.5V) on a Phidget OUT1000/OUT1001/OUT1002',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','Hotop',None)),u(QApplication.translate('HelpDlg','Hottop Heater: sets heater to value',None))])
        tbl_Commands.add_row(['&#160;',u(QApplication.translate('HelpDlg','Hottop Fan: sets fan to value',None))])
        tbl_Commands.add_row(['&#160;',u(QApplication.translate('HelpDlg','Hottop Command: motor(n),solenoid(n),stirrer(n),heater(h),fan(f) with n={0 ,1},h={0,..100},f={0,..10}',None))])
        tbl_Commands.add_row([u(QApplication.translate('HelpDlg','PID',None)),u(QApplication.translate('HelpDlg','p-i-d: configures PID to the values <p>;<i>;<d>',None))])
        helpstr += tbl_Commands.get_html_string(attributes={"width":"100%","border":"1","padding":"1","border-collapse":"collapse"})
        helpstr += "</body>"
        helpstr = re.sub(r"&amp;#160;", r"&#160;",helpstr)

        # autogenerated help pasted above

# ----- Cut above ---------------------------------------------
outfile = open('../output_files/eventbuttons.html','w')
outfile.write(helpstr)
outfile.close()
outfile = open('../output_files/help.html','w')
outfile.write(helpstr)
outfile.close()