---
name: Codespell
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: Test scenario tags
        required: false
        type: boolean
      environment:
        description: Environment to run tests against
        type: environment
        required: true
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements-dev.txt
      - uses: codespell-project/actions-codespell@v2
        with:
          path: src
          check_filenames: false
          check_hidden: false
          skip: ./.git,src/*.ts,src/coverage,src/build,src/dist*,src/htmlcov,src/*.spec,src/*.toml,src/includes/*.svg
          ignore_words_list: Abd,ser,alog,nd,iterm,dout,te,commandi,dout,exitt,currenty,exaust,controle,coment,controle,outweight,everytime,sade,weightIn,weightin
